### ISSUE TITLE
respond_to responds incorrectly if the mime type contains a +

### ISSUE THREAD

**Issue by dj2** [mynyml/rack-respond_to#1]
If you setup respond_to with a format that has a mime-type with a + in it then respond_to will fail to match the mime type. e.g.

<pre>
respond_to do |format|
  format.rss { "blah" }
end
</pre>

The RSS mime type is "application/rss+xml" which ruby's match method will return nil.

<pre>
>> a = 'application/rss+xml'
=> "application/rss+xml"
>> a.match(a)
=> nil
</pre>

Not sure if it's a valid solution, but gsubing the + to a _ will allow the match to pass.

<pre>
>> a = 'application/rss_xml'
=> "application/rss_xml"
>> a.match(a)
=> #&lt;MatchData "application/rss_xml"&gt;
</pre>

(the failure is caused by line 176 of respond_to.rb)

**Comment by dj2** [comment]
And of course, I missed the simpler solution.

<pre>
irb(main):005:0> a = "application/rss+xml"
=> "application/rss+xml"
irb(main):006:0> a.match(Regexp.escape(a))
=> #<MatchData "application/rss+xml">
</pre>

**Comment by mynyml** [comment]
Handle types containing special chars. Closed by 1537d7bb7f763ac133e6afcc5101cd383b244543

**Comment by mynyml** [comment]
Fixed. I also released v0.9.8 which contains the patch.

Thanks a lot for reporting the issue
